spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/task002?serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  flyway:
    url: ${DB_URL:jdbc:mysql://localhost:3306/task002?serverTimezone=UTC}
    user: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    enabled: true
    schemas: task002
    locations: classpath:db/migration
